### PR TITLE
Add functionality for getting related resources

### PR DESCRIPTION
**Pull request by jdenly**
When using Katharsis with Ember Data, it appears that the behaviour of related resources is not correctly supported. When Ember Data attempts to retrieve related resources links, as per http://jsonapi.org/format/#document-resource-object-related-resource-links, it uses a direct URL, not via the relationships URL. This triggers a findAll, rather than using the relationship repository.

Attached is a naive implementation that shows the correct behaviour for my use case inside of Ember Data, allowing Ember to request /entities/1/addresses and retrieve the addresses for entity 1. Without this change Katharsis retrieves all addresses.

### CODE REVIEW

**Comment by meshuga** [comment]
Hi,
Are you sure when you were creating the resources you did add the `@JsonToOne` or `@JsonToMany` annotation?
The resource that is responsible for the functionality is `FieldResourceGet` - https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/dispatcher/controller/resource/FieldResourceGet.java

**Comment by jdenly** [comment]
You're right, I misunderstood.

Looks like the issue I have is actually related to the naming of the nested resource. When it is named the same as a resource, the PathBuilder returns a ResourcePath instead of a FieldPath, leading to all the resources being returned instead of the filtered set.

The PR contains a test that illustrates what I mean.

**Comment by meshuga** [comment]
That's something I didn't consider ;)

**Comment by meshuga** [comment]
https://github.com/katharsis-project/katharsis-core/issues/62

**Pull request closed without merging**
