### PR TITLE
Feature/add automatic inclusion

### PR DESCRIPTION
**Pull request by zachncst**
For #108, created an annotation to automatically fetch included relationships, with tests.

### CODE REVIEW

**Comment by zachncst** [comment]
What's the temperature of this? Is it work me keeping it up to date with the changes/conflicts? I'm not interested in working on something if there is no chance of it getting merged.

**Comment by meshuga** [comment]
Hey. Thanks for the RP. It'll be merged.
I just had to think about this a little bit ;)
Could you resolve the conflict in `BaseControllerTest`?

**Comment by zachncst** [comment]
Thanks @meshuga, I'll fix the conflict in a bit.

**Comment by corrspt** [comment]
@zachncst With this PR, does it mean that any relationship that I might want included needs to have the annotation? 
If I'm reading this correctly I would want to add all the annotation to all relationships to be able to take advantage of this, no?

Will this work when fetching a list of resources, or only when fetching a single resource?

Awesome contribution by the way!

**Comment by zachncst** [comment]
Yes, by attaching the annotation the relationships then can be automatically looked up. This means that you can even fetch children of children ex) include=foo.bar.baz

In the example above. If foo and bar have the annotation, but baz does not it will fail to look up baz.

This gives you some control over what can be done from an include stand point so you don't have crashing servers from load.

**Comment by meshuga** [comment]
I like this feature mostly because of this annotation!

**Comment by zachncst** [comment]
I added it just for you @meshuga :-)

**Comment by corrspt** [comment]
Really cool @zachncst, really cool. Thanks! :+1:

**Comment by zachncst** [comment]
Thanks, I built it in my fork because our other engineer complained that it didn't do includes automatically. I figured it wouldn't be very difficult due to how well the relationships are defined and I was right. Only downside is you need to use the feature in a limited fashion. Some queries can take a long time if there is a many to many. It's best performing in a one to one or one to many relationship.

**Comment by zachncst** [comment]
Pull request has been updated.

**Pull request merged**
