### PR TITLE
Change serialization to use Jackson annotations

### PR DESCRIPTION
**Pull request by tdj-br**
Change serialization to use Jackson annotations

### CODE REVIEW

**Comment by tdj-br** [comment]
It was the past behavior, so I'm just keeping it as it was. Maybe others can explain why it's needed. There is a test that enforce that null attributes are not serialized.

**Comment by tdj-br** [comment]
This passed in all our tests. Please review and merge if possible. Thanks

**Comment by meshuga** [comment]
`ObjectMapper` can be extracted from `JsonGenerator#getCodec()` method. I don't want to create a new instance of ObjectMapper because:
* As @keithdmoore mentioned, it'll ignore global settings
* It might decrease performance - http://wiki.fasterxml.com/JacksonBestPracticesPerformance#A1._Reuse_when_appropriate

**Comment by tdj-br** [comment]
Thanks for the ideas. I'm doing it right now.

**Comment by tdj-br** [comment]
It's done. @meshuga @keithdmoore

**Comment by meshuga** [comment]
Great! I think it can solve so many other problems with attributes serialization.
Thanks for the work!

**Pull request merged**
