### PR TITLE
Fixes inclusion field name issue with kebab-case and other cases

### LINKED ISSUE #318: Kebab case for fields causes realtionships not to be found
Hello, 

I've configured Jackson to do kebab case for attributes and fields (transforms `fieldName` -> 'field-name' ). It does that to relationship fields also. 

However this breaks IncludeLookupSetter: 
````
13:04:48 [vert.x-worker-thread-1] DEBUG gr8pi.web.jsonapi.candidates.CandidateRestRepo - Find one
13:04:48 [vert.x-worker-thread-2] WARN  io.katharsis.resource.include.IncludeLookupSetter - Error loading relationship, couldn't find field candidate-assessments
13:04:48 [vert.x-worker-thread-2] WARN  io.katharsis.resource.include.IncludeLookupSetter - Error loading relationship, couldn't find field candidate-assessments
13:04:48 [vert.x-worker-thread-2] WARN  io.katharsis.resource.include.IncludeLookupSetter - Error loading relationship, couldn't find field job-match
13:04:48 [vert.x-worker-thread-2] WARN  io.katharsis.resource.include.IncludeLookupSetter - Error loading relationship, couldn't find field target-job
````

The problem is with `ClassUtils.findClassField(resource.getClass(), pathList.get(0));` which uses the kebab-case field instead of the real one.  

````
    private void getElements(Object resource, List<String> pathList, QueryParams queryParams,
                             RepositoryMethodParameterProvider parameterProvider) {
        if (!pathList.isEmpty()) {
            Field field = ClassUtils.findClassField(resource.getClass(), pathList.get(0));
            if (field == null) {
                logger.warn("Error loading relationship, couldn't find field " + pathList.get(0));
                return;
            }
````

### PR DESCRIPTION
**Pull request by ieugen**
* fixes #318 
* removed quotation marks from test parameter - as they do not seem to be compliant with JSON API documentation or examples (ResourceGetTets and CollectionGetTest)

### CODE REVIEW

**Comment by ieugen** [comment]
this should be applied after #321

**Comment by ieugen** [comment]
I've made an internal release with all patches applied and all things are good so far on staging.

**Comment by keithdmoore** [comment]
Does this fix the issue regarding the include that doesn't work in relationship repositories?

**Comment by ieugen** [comment]
Hmm, I'm not aware of that issue. 

It solves the issue when requesting to include a relationship resource in the response and the field name is different than the field name of your resource: 

`GET /tasks/?include[projects]=task&include[tasks-with-kebab-case]=comments`

````
class Project {
   private List<Task> tasksWithKebabCase;
}
````

Before this patch, the conversion from `tasks-with-kebab-case` to `tasksWithKebabCase` was not done so the field was not found.

**Pull request merged**
