### PR TITLE
Remove reflections dependency

### PR DESCRIPTION
**Pull request by staale**
This can probably do with some cleanup, I just hacked this together quickly. All tests still pass.

I am not a big fan of dependencies, and pulling in Reflections, seems to drag along a few other dependencies as well. This rewrite replaces Reflections with a small class that does only what Katharsis needs.

I am not using katharsis currently, but I am looking at it as a backend for my Ember frontend, which is why I did this change. If there are comments, I will see if I can find some time to clean this up further.

### CODE REVIEW

**Comment by meshuga** [comment]
Nice hack, but are you sure it's not going to break something?

**Comment by staale** [comment]
I have updated to fix the compilation issue and the classpath issue seen. However, I am not sure that this is the right approach any longer, as outlined in my commit comment.

**Comment by ieugen** [comment]
+1

**Comment by meshuga** [comment]
I think #101 solves this issue better

**Pull request closed without merging**
