### PR TITLE
Changed the attributes serializer to only filter attributes of the root element

### PR DESCRIPTION
**Pull request by tdj-br**
in order to fix katharsis-project/katharsis-core#246

### CODE REVIEW

**Comment by meshuga** [comment]
Great! But could you include a unit test?

**Comment by tdj-br** [comment]
Sorry, i'm probably not the right person to do it.

I have no experience with creating tests...

**Comment by keithdmoore** [comment]
@tdj-br Consider this a good opportunity to start learning how.  :-)

**Comment by tdj-br** [comment]
@keithdmoore Sure, as soon as time permits ;)

**Comment by keithdmoore** [comment]
@tdj-br I understand completely.  I also want your hard work to pay off by not allowing this problem to occur again.  Generally speaking, the person making a change is the person most familiar with the changes and is the best candidate to write the test(s).

**Pull request closed without merging**
